# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Specify the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: |
          ls ./
          dotnet build ./Domain/WFC2D/WFC2D.csproj --configuration Release
          dotnet build ./Tests/Tests/Tests.csproj --configuration Release
          dotnet build ./Web.Api/Web.Api/Web.Api.csproj --configuration Release
          dotnet build ./Web.Client/Web.Client/Web.Client.csproj --configuration Release
          echo "Building. ok"

      - name: Run unit tests
        run: |
          dotnet test ./Tests/Tests.csproj --configuration Release --no-build --verbosity normal
          echo "Testing. ok"

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Specify the .NET version you are using

      - name: Publish Web Client
        run: dotnet publish ./Web.Client/Web.Client.csproj --configuration Release --output ./publish

      - name: Deploy Web Client
        run: |
          # Add your deployment commands here
          # For example, if you're deploying to Azure, you might use:
          # az webapp deploy --resource-group <your-resource-group> --name <your-app-name> --src-path ./publish
          echo "Deploying Web Client..."
